\mainmatter
# Introduction

One way to conceive of scientific inquiry is as a form of strategy by which we try to confront theoretical constructs with empirical observation, aimed at aligning our beliefs as reliably as possible with what is true [@godfrey-smith2003, 161]. A lot remains to be unpacked from this sentence. However, for now it is enough to note that the empirical side of this equation is a critical point for archaeology, as the fragmented and uncertain nature of archaeological record means that there will always be a multitude of possible explanations that could account for any observed empirical pattern. Reducing this number of candidate explanations is first and foremost dependent on data, which in the case of archaeology are scarce.   

The goal of this study is to map and contrast empirical trends that have been deemed of importance for understanding past hunter-gatherer societies, drawing on the extensive material from the coastal Mesolithic of south-eastern Norway. Based on this, the project aims to culminate with the generation and presentation of some competing hypotheses concerning possible casual drivers behind the observed patterns. The project is thus inherently descriptive and exploratory. These inferential goals could perhaps be deemed unambitious by some. However, it is my belief that attempting to maintain a degree of inferential modesty is for the better of the discipline. Establishing true explanations of a past social reality is at best exceedingly difficult, perhaps impossible, and must be the result of cumulative and recursive efforts from entire research communities over time. It is not achieved by individual researchers. Accepting this social and cumulative nature of archaeological inquiry means that one can adopt a strategy to try to make ones research as open and amenable to scrutiny, extension, criticism and alternative approaches as possible. While easier said than done, an attempt at adopting such a strategy is done here.

As in many other areas of the world, the last few decades have seen a dramatic increase in the material generated by Norwegian archaeology. In terms of sheer number of sites and associated data, this is most marked for the coastal Stone Age material. Given that this increase in material is achieved on the back of public spending, it is arguably a disciplinary obligation to utilise this data for research purposes. While there are many possible arguments in favour of conducting archaeology at all, some more vague than others, the economic burden of archaeological practice is clearly easier to justify if the data we generate also informs the research we do. However, getting even a basic overview of this now vast material necessitates the use of quantitative and computational methods designed to handle, describe, explore, present, summarise and infer from such quantities of data. Following some early optimism in the 60s and 70s, such methods have, until recently, seen sporadic and relatively limited application for research purposes in Norwegian archaeology. 

Quantification offers standardisation and simplification, and by extension scalability and comparability. As with all disciplines concerned with the complexity of social life, whether past or present, archaeology also benefits from shifting perspectives that move between the nuance of particularities and the general trends illuminated by aggregated analysis. While there is perhaps a danger of the pendulum swinging too far, I would argue that the latter is at present still underdeveloped in Norwegian archaeology. With renewed and ongoing enthusiasm for such approaches, it is important that this is combined with a continually critical view of the answers these approaches can provide, and those which they cannot.

The great disciplinary benefit of archaeology, as compared to other disciplines concerned with the study of human societies, is by many argued to follow from the time depth it offers. Furthermore, while there are instances where the archaeological record allows what could be called glimpses into an ethnographic past of individual lives, the vast majority of the material we have access to is hampered by a degree of temporal uncertainty and lumping of events that necessitates a perspective that is developed to meet the nature and quality of the archaeological record on its own terms [@perreault2019]. Both fully utilising the archaeological material and playing to the strengths of the discipline is thus dependent on knowledge of the material available to us and it's quality, while also being dependent on developing methodologies fit for the purpose of elucidating long-term trends.  

## The quality of the archaeological data
The first two papers of this thesis are mainly aimed at contributing to the mapping and improvement of the quality of the archaeological record in coastal south-eastern Norway. The quality of the available data is fundamental for knowing what questions we can and cannot hope to answer about the past [@perreault2019]. Lower quality data will lead to averaging and smoothing, where for example a reduced temporal resolution can lead to chronological smearing that hides smaller scale oscillations and variability [@bailey2007]. The same principle extends to the dimensionality of the data, where loss will result in a reduction of variability and richness, for example in the composition of artefact assemblages. Loss and mixing are consequently more subtle effects than complete absence of data, which is more easily recognised. Furthermore, effects such as loss, mixing of past events and analytical lumping will most likely not impact the quality of the data in a uniform way. Taphonomic loss is likely to be more severe the further back in time one moves [@surovell2009a], and analytical bias from variable disciplinary interests or what geographical areas have been subjected to archaeological investigation will also skew our impression of the past [@binford1964]. Effects such as these have for example likely led to an underestimation of the cultural variability in, and similarly to an underestimation of the. Mapping the quality of the archaeological record is thus critical for knowing what past processes we would be able to discern, by extension what explanations we can hope to reject, and thus ultimately what questions we can hope to answer. 

## Model-based archaeology
Moving on from mapping the quality of the archaeological record in the two first papers, the final two papers of the thesis are more directly aimed at elucidating past cultural history by tracking developments in empirical trends that have been linked to the understanding of past hunter-gatherer societies. This will be done within a framework of model-based archaeology. Models are here seen as concrete and explicit representations of theory and data that act as mechanisms or mediators allowing for the coupling of the two dimensions [e.g. @clarke1972; @kohler2007; @lake2015]. The inferential modesty called for above follows from the defining characteristic that \'All models are wrong, but some are useful\', as @box1979[202] famously put it. 

Barton (2013) proposes a conscious and explicit modelling practice in archaeology for the same reasons. Traditionally, archaeological explanation is based on inductive and informal construction of narratives based on the inferential strategy of including as much data as possible and arriving at a percieved best-fit explanation. This is argued to have a tendency to result in explanatory complacency and high personal investment into the credibility of any given explanation. By embracing the explicit uncertainty and falsity that is a defining part of model-based approaches, this will therefore increase disciplinary progress, as it will lower the threshold for probing, adjusting and discarding one’s own models. 

## The hunter-gatherer model and the coastal Mesolithic
The concept of hunter-fisher-gatherers will function as a foundational model from which to derive empirical avenues to be explored and to propose possible causal drivers behind any observed patterns [cf. @warren2022, 29]. An example of a source from where this will be derived is the seminal work *The Lifeways of Hunter-Gatherers: The Foraging Spectrum* [@kelly2013]. In the introduction of the book, @kelly2013[4] states that it is aimed at providing its readers with 'some knowledge of the variation that exist among foragers and some idea of what accounts for it'. The employed hunter-gatherer model will thus decidedly be wrong. That is, it will not be a model that reflects the hunter-fisher-gatherers of Mesolithic south-eastern Norway. This is both due to idiosyncrasies in this specific context, but also because I will imperfectly derive and specify the model based on the vast range of archaeological and ethnoarchaeological work on hunter-gatherers as such. 

Another challenge in determining what empirical trends are of interest and how these are to be understood follow from the coastal setting. Historically, the work on world prehistory has focused on terrestrial contexts [@yellen1980; @bailey2004]. This also extends to the methodological realm, where for example the use of Geographical Information Systems (GIS) in archaeology has predominantly been used in terrestrial contexts [see e.g. @conolly2006]. This is especially pertinent for the coastal Mesolithic of Scandinavia, which is characterised by dramatic sea-level change throughout the period [e.g. @bjerck2008; @astrup2018]. Out-of-the-box procedures are therefore often not directly applicabale and have to be adjusted to meet the demands of a geologically dynamic coastal context.     

## Open research and reproducibility

In making the case for open sharing practices in archaeological research, @marwick2017[426] compares the principle of artefact provenciancing with dissemination of raw data and methods. Without knowing the provenance of an artefact, it's archaeological value is practically none. Comparatively, by openly sharing underlying data and code, other researchers can assess the procedures that have led to the results of a study. Apart from facilitating an evaluation of its reliability, this allows others to extend on the analysis and the employed data, to learn and reconstruct how methods are implemented, and to atttempt repeating all or parts of the analysis. Open research is thus integral to archaeology as a cumulative research endevour as it will both increase the freqeuency of model rejection and adjustment by allowing others to explore their inner workings, and because it will increase the pace of method and tool sharing.  

This thesis has been written in its entirety using the R programming language [@rcoreteam2021]. Unlike for example mouse-driven computational analyses, this means that an unambigous record of the entire analytical pipeline is recorded in the form of programming scripts, moving from the initial loading and cleaning of raw data, through to analysis, visulisation and final reporting of results. Given the large amount of analytical choices that have to made in the course of an analysis, this can never be adequately presented in prose. Furthermore, what a researcher believes they have done need not correspond with what they have actually done. The high-resolution analytical record that is the programming script makes this entirely transparent. All data, programming code, figures and text used in this thesis is freely available in online repositories on GitHub (https://github.com/isakro) and on the Open Science Framework (https://osf.io/s6tb5). A complete overview with links to the various online archives associated with the individual papers and this synopsis is provided in Table \@ref(tab:op). 

```{r op, echo = FALSE, out.width = "500px"}
dat <- data.frame(titles = c(
        "Synopsis",
        "Paper 1",
        "Paper 2",
        "Paper 3",
        "Paper 4"),
         preprint = c("",
                      "",
                      "",
                      "osf.io/cqaps",
                      ""),
         repositorygit = c("",
                           "github.com/isakro/assessing.sealevel.dating",
                           "",
                           "github.com/isakro/exploring-assemblages-se-norway",
                           ""),
         repositorydoi = c("",
                           "",
                           "",
                           "osf.io/ehjfc", 
                           ""))

knitr::kable(
  dat, booktabs = TRUE,  linesep = c(""), escape = FALSE,
  caption = "Overview over code and data repositories and preprints.",
  col.names = c("Text", "Preprint", "GitHub repository", "OSF repository")
)
```

## Overview of papers
### Paper 1: *A simulation-based assessment of the relation between Stone Age sites and relative sea-level change along the Norwegian Skagerrak coast*
The first paper offers an approach for integrating the various sources of uncertainty associated with reconstructing the relationship between ^14^C-dated archaeological phenomena and past sea-level change. This is used to quantify the distance between Stone Age sites and the prehistoric shoreline within the study area. That coastal sites would have been located on or close to the prehistoric shoreline is a fundamental premise in Norwegian Stone Age archaeology, which in combination with reconstructions of past shoreline displacement is frequently used to date the sites based on their altitude relative to the present day sea-level---a method known as shoreline dating. The findings of the paper largely reflect the development proposed in the literature, with a predominantly shorebound costal settlement in the Mesolithic, followed by a few sites being located some distance from the shoreline at the transition to the Early Neolithic (c. 3900 BCE) and a more decivise shift away with the Late Neolithic (c. 2400 BCE). The result of this analysis is used to propose a refined method for shoreline dating sites older than the Late Neoltihic which accounts for uncertainty as related to the displacement data and the distance between sites and the shoreline when they were in use. 

### Paper 2: *Relative sea-level change in the inner Oslo fjord*
The second paper is geoarchaeological contribution tentatively titled *Relative sea-level change in the inner Oslo fjord*. The main goal of the paper is reconstruction of past relative sea-level change in the Oslo area. The last shoreline displacement curve to be developed for Oslo is from the 1950s, and major methodological advances, including the advent of radiocarbon dating means that this is ripe for an update. from a geological perspective, these results will be of value for understanding the interaction between deglaciation, istostasy and eustasy, as well as for the mapping of marine sediments and landslide hazards. From an archaeological perspective the reconstruction of the past landscape of the region will be used to extend the evaluation of the relationship between archaeological sites and the past shoreline, drawing on the first paper of the thesis. Furthermore, the inner part of the fjord has been strategically important up until the present day. Of most immediate relevance here is how this pertains to the relationship between deglaciation, sea-level change and the first human presence in Norway [@glorstad2016]. Through the geological reconstruction, the second paper of the thesis will thus contribute a better framework with which to map human-environment interaction, as well as improve our chronological knowledge of the archaeological record by offering a firmer foundation on which to shoreline date sites in the area.   

One round of fieldwork was conducted in October 2021, followed by a week of laboratory work at the Geological Survey in Trondheim in November 2021. This resulted in isolation contact determined for three basins, with 8 ^14^C-dates. A last round of fieldwork will be conducted in June 2022.

### Paper 3: *Exploring the composition of lithic assemblages in Mesolithic south-eastern Norway*
The second part of the thesis is aimed at a more direct investigation of past cultural history. The third paper of the thesis is an exploratory study aimed at identifying variability in the contents of a set of lithic assemblages. The main goal of the paper is to evaluate the typo-technological framework currently in use in Norwegian Mesolithic research, and to assess the temporal development for variables that have been linked to variation in land-use and mobility patterns. It is demonstrated that elements of the so-called Whole Assemblage Behavioural Indicators [e.g. @clark2017] align with previous research into developments of mobility patterns in Mesolithic Norway, suggesting that the WABI could be a relevant framework also in this context. This is specifically reflected in a negative relationship between density of lithics and the proportion of secondarily worked lithics over time, which is taken to reflect a transition from a more curated to a more expedient technological organisation with the transtion from the Early Mesolithic (c. 8200 BCE), in turn argued to follow from a shift in land-use patterns and a overall reduction in mobility.

### Paper 4: *Inductive multi-proxy analysis of Mesolithic demographics along the Norwegian Skagerrak coast*
Unpacking the complex interplay between environmental conditions, settlement patterns and population density has been deemed of fundamental importance to archaeological inquiry [@shennan2000; @french2016; @riede2009a]. The fourth and final paper of the thesis has the provisional title *Inductive multi-proxy analysis of Mesolithic demographics along the Norwegian Skagerrak coast* and is aimed at combining findings from the previous papers to evaluate the interplay between empirical indicators suggested in the literature to be related to these dimensions. Concretely, the paper aims at elucidating the relationship between variation in relative population size as potentially reflected in the density of shoreline dated sites over time and the radiocarbon record. These proxies will be linked to development of the variables derived from the WABI and variation in the rate of sea-level change, as both are conceivably related to mobility and land-use patterns. 

