# Background
This chapter presents the context of the study


## Environmental setting

The environmental setting for the Mesolithic in Scandinavia is first and foremost defined by the end of the Weichselian and the retreat of the Fennoscandian Ice Sheet [see @skar2018; @skar2022:106--109]. Most pronounced of the resulting environmental impacts is the melting of the ice sheet itself, corresponding eustatic sea-level change and isostatic rebound, changes in the ocean currents, as well as the developments of the Baltic Sea, which transitioned between being open and closed off from the North Sea. These developments form a  backdrop to which human societies developed. 

The global climate reconstructions based on oxygen isotopes from the Greenland ice cores  gradual heating interspersed with cold events c. 10 300 cal BP, c. 9200 cal BP and 8200 cal BP. However, how these events played out locally and what consequences this development had for local ecosystems and human populations appears to vary quite dramatically across Northern Europe and thus cannot be assumed a priori to have been of relevance or concern for the societies dealt with in this thesis. 

### Climactic oscilations


Regional increase in temperature and perticipation rates from the early Preboreal, followed by mild winters and humid conditions in the Boreal with the Holocene Thermal Maximum, locally dated to c. 6400--2400 BCE.  

At the transition to the Boreal, the vegetation in the region goes from arctic vegetation characterised by to  

### Sea-level change
Following the retreat of the ice


Depending on the scale of, sea-level change can impact not only the habitational suitability of any individual location, but can have far-reaching effects that impact shoreline morphology, drainage systems and [e.g. @gross2018; @astrup2018]. While the at times dramatic magnitude of these changes would have required a response from human populations inhabiting the impacted areas, it is by no means given that these would have negative consequences for these societies. In fact, areas impacted by sea-level change can be attractive for hunting, fishing and gathering precisely because of these factors. The study of human response to sea-level change should therefore not assume that this would be the result of. How sea-level change impacts the population of any given area will thus depend on a wide range of factors pertaining to the amplitude of shoreline displacement, the topographic setting, and the nature of the societal systems which respond to these changes.

## The Norwegian Mesolithic

Having presented the environmental developments of the period, the following section gives a general outline of how chronological and societal developments in the Mesolithic have been characterised and understood archaeologically. The first focused research on the Norwegian Mesolithic is ascribed @hansen1904, who studied the material that @brøgger1905 later saw as a defining element of the Nøstvet culture [@bjerck2008:61]. In 1909, Nummedal made discoveries of flint artefacts in western Norway that were deemed likely to have an earlier date than the Nøstvet material [@rygh1911; @nummedal1912], and which led to the subsequent definition of another cultural unit termed Fosna [@nummedal1924]. Nummedal later also discovered material in northern Norway that had parallels with but was considered distinct from Fosna and which was given the label Komsa [@nummedal1927]. While the geographical and temporal relationship between these cultural units were recognised as unresolved and was subject to much debate, the common understanding was for many decades that southern Norway was defined by the chronologically sequential phases Fosna and Nøstvet, while Komsa was seen as defining of the entire Mesolithic period in northern Norway [see e.g. @indrelid 1978:147]. In renewed debates in the 1970s, that were arguably founded on a better understanding of lithic technology than much of the preceeding debates [@bjerck1996], signifcant .  @mikkelsen1975 suggested a tripartie division of the Mesolithic in south-eastern Norway by dividing the period into the Early, Middle and Late Mesolithic. This was in turn also subdivided 

 
The traditional chronological framework for the Mesolithic of south-eastern Norway has followed along the general lines of that presented by @glørstad2010[23, see table]. Recently this has been. The degree to which the chronological shifts are. While they form a natural frame for the narrative structure of this text, these should not been seen as the impact of strict periodisation is to some extent counteracted by treating. This will be treated in more detail in the next chapter 

In a comprehensive reassessment that also includes results from the last decades of excavations, @reitan2022 has recently suggested a new chronological framework for the Mesolithic period in south-eastern Norway [also @reitan2016]. As his focus has mainly been on technological and typo-chronologcal developments, and given their recent date of publication, this chronological framework has yet to be comprehensively evualuated in terms of correspondence with other societal developments. The presentation of major chronological trends in the sections below thus follows the traditional periodisation. However, in the discussion chapter, the results of this thesis will also be seen in relation to the framwework suggested by Reitan.

The following sections will outline general societal developments believed to characterise the Norwegian Mesolithic, divided into the periods Early Mesolithic (EM; 9300--8300 BCE), Middle Mesolithic (MM; ) and Late Mesolithc (LM; . While focus is on south-eastern Norway, reference to a wider context and neighbouring regions in Norway and Sweden when perspectives 

### The Early Mesolithic (9300--8300 BCE)

The first human presence in Norway is recorded from around 9300 BCE, which marks the start of the EM. A central discussion has concerned whether people first migrated into the area of present-day Norway from a route along the coast of western Sweden, from the north-east along the northern-Norwegian coast [@bjørn1929], or across the Norwegian trench to south-western Norway from the the North Sea Plain [Doggerbank, @odner1966]. The most recent evidence suggest that a crossing from Doggerbank would not have been feasible due to the distances involved at the time [@glorstad2016; @glorstad2017]. The present consensus is therefore that the earliest human dispersal into present-day Norway is likely to have originated on the coast of western Sweden around 9500--9300 BCE [e.g. @glorstad2020; @bjerck2008]. From here, human occupation is believed to have rapidly extended along most of the Norwegian coastline, while a north-eastern migration reached Kola and northern Norway some time before 9000 BCE [@manninen2021]. These two routes are associated with the genetically defined 'western' hunter-gatherers that migrated from the south, and 'eastern' hunter-gatherers migrating from the north [@gunther2018], each identifiable also in terms of distinct material culture and technological traits [@manninen2021].

 <!-- (f.eks. Bjerck 2008c:74; Glørstad 2010a:91-93) -->

Pioneer sites in Norway and Western Sweden have traditionally been ascribed the archaeological cultures or technocomplexes Fosna and Hensbacka, respectively. Today these are seen as representing the same phenomena [e.g. @bjerck2008, 75]. Fosna/Hensbacka sites are to hold fairly homogeneous lithic inventories, and are held by many as having a common origin tracing back to South-Scandinavian and North-European Palaeolithic Ahrensburg groups (e.g. @bjerck2008; @schmitt2009; @band-andersen2012; @fuglestvedt2012; @riede2014, 564]. The analyses of artefact inventories, the presence of high-quality South-Scandinavian flint, and the chronological support of radiocarbon dates and shoreline dates have in sum led to the consensus on this continental connection (see Fischer 1996; Schmitt et al. 2006; @fuglestvedt2007; @fuglestvedt2009; @bang-andersen2012; @glørstad2016). The similarities has led @fuglestvedt2012[8] to propose that the terms Fosna/Hensbacka be abandoned altogether, in favour of Ahrensburg, as this would accentuate the continental elements that appear so defining for these pioneer sites. Although this has been met with varying degrees of enthusiasm (e.g. Åstveit 2014 with comments), particularly by those emphasising the strong marine orientation of the Fosna/Hensbacka, there has also been the occasional use of variations such as 'coastal Ahrensburg' to denote the Fosna/Hensbacka (@prøsch-danielsen1995). Following a recent analysis of lithic inventories from the transition from the Paleolithic to the Mesolithic in Northern Europe, and comparison with Fosna/Hensbacka sites in Norway and Sweden, @berg-hansen2017[] has argued that the Fonsa/Hensbacka sites have a clear similarity with EM Maglemose sites in Denmark. While there are elements of this technology that point back to the Ahrensburg, there is also a clear break with the Paleolithic technology. She therefore argues that these societies should, as with the Maglemose, be considered Mesolithic and not a northern continuation of Palaeolithic life-ways. At any rate, these discussions do go to show that there is a clear affinity between the first human population on the Scandinavian Peninsula and continental hunter-gatherer groups.

To account for this apparent pan-regional homogeneity, a central question is by what process Norway and western Sweden were initially colonised [e.g. @bjerck2009; @schmitt2009; @bang-andersen2012; @fuglestvedt2012; @glørstad2016; @berg-hansen2017]. An important aspect in this regard is the fact that the coastal areas in western Sweden and Norway were largely ice-free early on, and must have been rich and desirable areas in terms of resources [@bjerck1996; @bjerck 2009; @bang-andersen2012; @glørstad 2016]. Bjerck [@bjerck1996; @bjerck2009, @bjerck2017] has explained the fact that people did not start exploiting these regions until around 9300 BC with reference to less developed marine subsistence strategies among North-European hunter-gatherer groups. The coastal location of the majority of Fosna/Hensbacka sites will undoubtedly have necessitated extensive adjustment to marine environments, including by the use of boats. Following the delay induced by this, the hunting of seal, conceptually not that different from the hunting of large terrestrial mammals, might have spurred an increased development of boating technology, while at the same time lending itself to the continued use of a continental artefact inventory [@Bjerck 2009; @bjerck2016]. Proficient and effective use of boats might in turn have resulted in a relatively rapid colonisation of Fosna/Hensbacka areas, possibly as fast as over a period of only 200--300 years [@bjerck1994; @bang-andersen2012], providing a possible explanation for the homogeneous assemblages. These could reflect mobility of a kind not allowing for familiarisation with local resources for tool production, nor the development of distinct inventories adjusted to various geographical settings. The assemblages might therefore represent a sort of catch-all toolkit, suitable to meet the variable demands of a 'pioneer condition' [@bjerck2017; see also @breivik2016]. Furthermore, @berg-hansen2017[232] has argued that the homogeneity in the lithic inventories could be related to relatively high population numbers with closely knit social ties, which in combination has enabled this technological conservatism. Homogeneity and continuity in lithic technology over vast expanses of Scandinavia would be difficult to envision with a thinly spread population consisting of more isolated groups.   

In general, the Early Mesolithic in Norway is understood as consisting of highly mobile groups [@bjerck1996; @bjerck2008; @fuglestvedt2012]. As there is little organic material on which to base inferences on subsistence, there is little to go on when attempting to determine what available resources made up the diet of people in Norway in the first centuries of human occupation. The EM sites are mainly found along the coast, and so there is little doubt that aquatic resources have played an important role [@bjerck2008; @bang-andersen2012; @fuglestvedt2014]. It can, however, not be excluded that land mammals, and various species of fowl and flora have not also been important constituents of the diet [@åstveit2014; @fuglestvedt2014]. While the settlement is focused on the coast, there is also a marked presence in the mountain regions of south- and north-western Norway from a very early stage [@hagen1963; @bang-andersen2012], which are believed to have been related to the hunting of reindeer. Given the, an analysis settlement patterns has been argued to provide a possible way to make general inferences to subistence. 

The coastal EM sites have been characterised as typically situated on small islands and been exposed to 


As a counterpoint, in a recent study I found that the settlement patterns in a subregion of south-eastern Norway was fairly similar across the EM, MM and LM [@roalkvam2020]. Of the considered variables, the most important driver of settlement patterns was found to be degree of exposure, where the sites were found to be located with relatively open immediate surroundings while at the same time being sheltered from larger expanses of open sea. However, one of the locational patterns that was not considered was the location of the sites within the wider landscape. The term exposure has been used to denote both how commanding the view would have been from the sites and how exposed the sites would have been to wind and wave-action [@svendsen2014], but has also pertained to their location relative to deeper fjords and outermost coast. It has been argued that EM sites would have mainly been located on the outer coast, and that the fjords were not utilised until a later stage. This is argued to reflect a focus on the hunting of marine mammals, especially seal, in the EM.     


Coupled to this discussion is also what motivated the initial human dispersion into these territories. 

The blade technology of the Early Mesolithic is based on single- and dual-platform one-sided cores, typically by means of direct percussion [@solheim2020].  

Some central discussion that linger in the literature concerned with the period pertains to the nature of the first colonisation of Norway. Did the coastal areas represent an unprecedented opportunity in an extended Garden of Eden, or an obstacle to be overcome. Furthermore, discussions pertaining to the degree of mobility and unified nature of lithic assemblages 


### The Middle Mesolithic (8300--5600 BCE)
While the Middle Mesolithic (MM) was defined as a separate typo-chronological phase in the 1970s, Bjerck stated as late as 2008 that the period was associated with a limited archaeological material, thus posing an analytical challenge [@bjerck2008, 92--98]. This is in part related to sea-level transgressions in this period along the coast of southern and western Norway, and the fact that MM sites are located at elevations that are typically not impacted by . However, investigations in recent years have dramatically changed this picture, not least in eastern Norway, which has not been subject sea-level transgressions. 

@bjerkc2008, notes that period is characterised by a degree of regionalisation that is not evident in the EM material. 

In the Middle Mesolithic blades are produced from conical and sub-conical cores with a single platform using pressure and indirect percussion [@damlien2016; @solheim2020].

### The Late Mesolithic (5600--3900 BCE)

Blade production in the Late Mesolithic is characterised by the introduction of handle cores [@eigeland2015]. As pointed out by @solheim2020[4], this involves a shift from cores that will result in blades of gradually diminishing size as the core is exhausted in the EM and MM, to cores that result in blades of a uniform and comparatively small size (i.e. microblades). 

## Coastal hunter-gatherers
As representing adaptation to diverse environments, marine habitats are deemed an essential component in the evolution of modern humans and determining for the spread of the species across the globe. In Palaeolithic archaeology the coast has traditionally been seen as a hostile environment for early hominins. Marine habitats and resource-use has also been characterised as a central for the evolution and 

A note should be made on the fact that in the literature the terms *coastal adaptation* and *coastal resource use* are sometimes taken to imply different and quite specific things [see e.g. @faulkner2021; @marean2014; @will2019]. Coastal resource use is in this understanding seen as something that is conducted sporadically or occasionally, and will have limited transformative feedback effects on the life-ways of the societies in question. Conversely, coastal adaptation involves a degree of coastal engagement and commitment that has an altering effect on these societies. I do not use the terms in this manner here. The conceptual distinction is certainly an important one, especially as marine exploitation is believed to potentially, but not necessarily [e.g. @erlandson2001], lead to technological ratcheting and increased societal complexity. However, these quite specific connotations of the terms stand in danger of leading to misunderstandings for readers that have another understanding of adaptation, which need not be defined by some threshold in the intensity of coastal engagement. One response to the specifics of a given marine habitat might for example be movement and extended use of terrestrial resources, which would fall within a more inclusive definition of adaptation to a given coastal environment. While the above division might have merit in some analytical settings, the dependence on marine resources is arguably better understood along a continuum that I believe this might unnecessarily dichotomise. 




Inland
