# Analytical background {#chapter3}

The last chapter outlined the environmental and archaeological background for the thesis. This chapter presents underlying analytical concepts that have motivated the research questions asked and the methods employed in the undertaken studies. The first part of the chapter outlines some issues that are fundamental to archaeology in general, pertaining to dimensions such as the quality and resolution of the empirical data, chronological frameworks and cultural taxonomies, and presents some methodological and conceptual ways in which these can be contended with. The last part of the chapter moves on to consider dimensions and characteristics of hunter-gatherer societies that are often considered to be of central importance for understanding the variation that has existed among these societies. The section on hunter-gatherers thus pertains more directly to what cultural historical dimensions the thesis attempts to elucidate. 

## The quality of the archaeological record

Underdetermination and equifinality are two related concepts that concern the degree to which empirical evidence can be drawn on to adjudicate between competing explanations. Equifinality pertains to the case where different processes have the same empirical result, while underdetermination pertains to the case where the available empirical evidence can be the result of different processes [e.g. @okasha2016, 66--70; @perreault2019, 1--2; @psillos1999, 162--182]. The degree to which this occurs therefore impacts the hope we have of ever choosing between competing explanations, and is especially pertinent for archaeology as we deal with a fragmented empirical record fraught with various systematic and un-systematic biases that impact the quality of our data, in turn leading to the underdetermination of potential explanations.

Due to underdetermination, the quality of the data available to us is consequently fundamental for knowing what questions we can and cannot hope to answer about the past [see @perreault2019]. Lower quality data will lead to averaging and smoothing, where for example a reduced temporal resolution can lead to chronological smearing that hides smaller scale oscillations and variability [@bailey2007; @daems2023]. The same principle extends to the spatial scale, where a lower empirical coverage means that answers to questions pertaining to processes operating at the scale of individuals, sites or smaller regions might not be empirically tractable, and a larger view might be necessary to bring into view a process of interest, thus determining what processes we can hope to unveil. Furthermore, this issue also pertains to what @perreault2019 terms the dimensionality of the data, that is, the features that can and have been recorded for a set of observations -- for example stable isotope characteristics of human remains. Loss or otherwise reduced dimensionality can here result in a reduction of variability and richness, impacting for example the perceived characteristics of artefact assemblages. 

Furthermore, loss and mixing can sometimes be more subtle effects than complete absence of data, which can potentially be more easily recognised. Moreover, effects such as loss, mixing of past events and analytical lumping will most likely not impact the quality of the data in a uniform way. Taphonomic loss is likely to be more severe the further back in time one moves [@surovell2009a], be dependent geographically contingent environmental impact on preservation, and analytical bias following for example from disciplinary interests or what geographical areas have been subjected to archaeological investigation will also skew our impression of the past [@binford1964]. Mapping the spatial and temporal quality of the archaeological record is thus critical for knowing what past processes we would be able to discern, and by extension what kind of archaeology we can hope to do. For these reasons, a central aim of this thesis is to contribute to mapping the data available from the coastal Mesolithic of south-eastern Norway.

### Digital and computational archaeology
Given the large amounts of data that have been and continue to be generated by Norwegian Mesolithic archaeology, contending with this data at even the most basic level necessitates the use and development of computational methods designed to handle this, in the words of @bevan2015, \'data deluge\'. Furthermore, most of the data generated by archaeology today is to varying degrees digital in nature, legacy data is increasingly being digitised, and digital tools are used at all levels of archaeological practice. Therefore, digital and computational methods are fundamental and intrinsic to modern archaeology, irrespective of the scale we are operating on. As @morgan2012[534] have stated: \'we are all, whether we like it or not, digital archaeologists\'. 

Given this dependency on computational and digital methods, it has been argued that it is not enough for archaeologists to passively employ these technologies or to critically assess their development from afar. Archaeologists have to become active, informed and reflective participants in the development of new technologies, and in the assessment and creative application of those that already exist [@llobera2011]. As the philosopher of technology @ihde2004 has argued, it is necessary to some degree to \'go native\' [cited by @huggett2015, 88]. All four papers of this thesis can be said to contribute to this through the exploration, development and open dissemination of methods and technologies for the purposes of handling data and casting this as evidence for understanding the Mesolithic of south-eastern Norway.  

There can be merit to an exploratory accumulation and systematisation of the available data in its own right, both to get an overview of the processes we can hope to explain, and as it can reveal patterns in archaeological categorisation and help identify, and potentially average out erroneous data points or idiosyncratic and random variation [see e.g. @cooper2016; @hamilton2022]. However, more data will not by itself offer any meaningful insight. Discussing this in the context of so-called \'big data\' in archaeology, @huggett2020 states that  \'digital data not only offer possibilities but may also constrain actions, they limit as well as enable, and this may not always be recognized in the thrill of the revolutionary discourses surrounding Big Data and the lack of a proper data gaze.\' While seeing data as given, free of influence from our preconceptions is a well-known fallacy and a long held criticism in archaeology, several authors have expressed concerns with the degree to which developments in digital technology may lead to an over-enthusiasm that neglects the messy, fragmentary and complex nature of archaeological data, and that this can lead to fetishisation of digital data following from its availability, tractability and often elegant-seeming results [see e.g. @haciguzeller2012; @huggett2020; @solli2007]. 

While large amounts of data do not offer a way to side-step the fundamental issues with archaeological evidence, there is nonetheless decidedly value to evaluating data at multiple scales. Not only can this reveal patterns and processes that operate at some scales and not at others, but different scales of perspective can also feed back to each other and reveal biases or inconsistencies. Furthermore, by drawing on for example @kuhn1970 and the later work of @galison1997, several authors have argued that the development and employment of digital and computational tools by itself impacts the fundamental practice of doing archaeology [@grosman2016; @schmidt2020] -- an effect that extends beyond the scale these methods can operate on. Active, informed participation and sharing of digital and computational tools is therefore likely to advance archaeology by leading to a situation where  \'familiar objects are seen in a different light and are joined by unfamiliar ones as well\' [@kuhn1970, 111]. 

This promise is of course also dependent on the context and ways in which data has been recorded and been made available [@huggett2014; @cooper2016]. A central issue with digital data is therefore to avoid naive empiricisms and to offer transparency with regards to its creation, manipulation, handling and finally with how it is cast as evidence. This will allow ourselves and others to assess how these steps might influence the arguments that are made. The ways in which these issues are attempted to be tackled in the context of this thesis will be laid out in more detail in Chapter \@ref(chapter4).

## Chronology, cultural taxonomy and modifiable analytical units
\sectionmark{Analytical units}

The study area of this thesis, situated within south-eastern Norway, is for the most part believed to have followed a similar trajectory in terms of overall cultural-historical developments and expressions of material culture through the Mesolithic. At least within the analytical detection limit that has characterised the field thus far. What has been of greater concern is the temporal transition between the occurrence of cultural taxonomic elements within the region. In Norwegian Mesolithic research more widely, however, the question of both regional variation in material culture and its timing has led to discussions of whether a concept known as \'chronozones\' has any merit as a framework for systematising the archaeological material. This is a concept that has remained marginal in archaeology as a whole, but is used by several practitioners in Norwegian Mesolithic archaeology [e.g. @bjerck2008; @nyland2016; @fretheim2017; @breivik2018; @fuglestvedt2018; @skar2018], and is related to fundamental issues faced within archaeology.

The concept originates in a paper by @bjerck1986, in which he attempts to tackle the distinction between the archaeologically defined cultures of Fosna and Nøstvet in the context of Western Norway. Instead of an ever-continued nuancing of these terms as more variation and idiosyncrasies are encountered in the archaeological record, @bjerck1986[117--119] instead suggests a division of the Mesolithic period into a series of time-intervals denoted chronozones, originally at a resolution of 500 years, which he argues could facilitate a pan-Scandinavian framework for approaching the Mesolithic [@bjerck2008, 72--73]. The concept of chronozones is taken from the geosciences, where the term is used to denote stratigraphic layers that formed over the same specific time-span on a regional or world-wide scale, known from geochronological units such as for example the Preboreal, Boreal and Atlantic time-intervals [e.g. @salvador1994, 83--85]. Bjerck's motivation for adapting this to archaeology is to form a framework that is neutral with respect to cultural variation across space and time. He argues that traditional archaeological units of analysis, typically denoted by terms such as cultures or techno-complexes that are discretely delineated in time and space, has led to an artificial partitioning of the archaeological material that is less open to gradual temporal change and spatial variation -- an issue that has been contended with by many archaeologists through the years [e.g. @butzer1982, 279--320; @childe1956, 121--125; @smith1992; @clark2009; @roberts2011; @reynolds2019]. Bjerck argues that the use of neutral 500-year time-intervals will reduce the degree to which analyses will overemphasise homogeneity within, and exaggerate differences between such analytical units. To further illustrate the issues @bjerck1986 attempted to tackle, it is useful with a detour via the concepts of the Modifiable Areal Unit Problem (MAUP), as taken from the field of geography [e.g. @harris2006], and its recently coined temporal equivalent, the Modifiable Temporal Unit Problem [MTUP, @bevan2021].

### The MAUP and MTUP {#modifiable}

The scale problem, as its often called, is central to geographical research. This follows from the scale that is chosen in the necessary generalisation of continuous phenomena, the dependency of this generalisation on the density of sampling points, and the variable spatial scales that different phenomena operate across [@harvey1968]. Some central implications @haggett1970 identifies in relation to this is the *scale coverage problem*; related to the choice of variable sampling designs and intensities for undertaken studies, the *scale linkage problem*; the problem of comparing results captured at one spatial scale with those captured at another, and the *scale standardisation problem*; the issue of how data that have been captured on varying spatial scales are adjusted to a common scale [@harris2006, 46]. Extending on the last problem, @haggett1970[177--179] shows how adjusting the boundaries used to delineate the originally retrieved data can have substantial consequences for any basic comparisons of the occurrence of phenomena within these units, which is the issue that underlies the MAUP.   

The MAUP is defined by @heywood2002[8] as \'a problem arising from the imposition of artificial units of spatial reporting on continuous geographical phenomenon resulting in the generation of artificial spatial patterns\' and is an issue that underlies most if not all analyses that draw on areal data [@harris2006, 48]. A common example from archaeology is the areal unit of the site, the delineation of which typically follows some notion of concentration of artefacts. However, the density of artefacts over a landscape can be conceived of as a continuous phenomenon, and so its definition will always be modifiable and subject to choice, whether it follows from some kind of statistical procedure or a more intuitive definition [e.g. @dunnell1983; @thomas1975; @hodder1976, 17--19]. The same problem extends to the smaller scale, such as with the definition of site features based on the concentration of charcoal, and up in scale, such as to the definition of archaeological cultural areas. How these units are defined will impact the most basic comparison between them. Given the arbitrariness and potential variation that might exists in the aggregation procedures underlying our areal units, it is therefore always a danger that discovered patterns could simply be artefacts of the aggregation technique.     

These issues can also be extended to the temporal dimension, which @bevan2021 have recently demonstrated in the context of archaeology by illustrating how periodisation involving lumping and splitting of phenomena within disjoint time-intervals have analytical consequences that remain under-appreciated within the discipline. First, employing strict cut-offs between temporal units -- units that often also vary in their duration -- has major implications for comparison between these units, and can, as @bjerck2008[73] also notes, lead to an artificial and inadvertent overemphasis of the transition between these. Basic operations such as comparing counts will be biased by variable duration of these units, and the position of breaks between them can be highly influential to the appearance of the frequency distribution of events over time.

Building on @crema2020, @bevan2021 further define three types of uncertainty associated with this archaeological practice. The first is *phase-assignment uncertainty* -- how certain can we be that a given phenomenon can be ascribed to a given phase. The degree to which this varies between different material categories means that it can be difficult to compare their frequency across archaeological phases. As was found in the third paper for this thesis [@roalkvam2022], the occurrence of formal tool types at the Mesolithic sites in the study appears to be greater further back in time. This as opposed to younger sites, which are to a larger extent dominated by generic debitage that can be more difficult to assign to a specific phase. This can have implications for how many sites are ascribed earlier periods, and, by extension, could impact a comparison between phases. The second pertains to the *within-phase uncertainty*, the degree to which the occurrence of various phenomena have an equal likelihood of occurrence throughout an archaeological phase. For example, in typological discussions for the Norwegian Mesolithic, the occurrence of different artefacts types is in practice typically treated as having a uniform occurrence within a given time-span.  The final dimensions @bevan2021 highlight is the *phase boundary uncertainty*, which pertains to the start and end points of the archaeological phases themselves. As these are typically defined by a complex interplay of multiple cultural phenomena, they are seldom meant to operate on the scale of individual years but will in practice often be operationalised as such. 

### Archaeological chronozones

While possible methodological ways around these issues are presented in the works cited above, neither the MAUP nor the MTUP have any clear solutions, and the magnitude of their impact will depend on the given research question and accompanying analytical scale. However, their formulations arguably form a better frame for understanding these issues than the concept of chronozones. I argue here that chronozones can instead obfuscate the distinction between the temporal and the spatial scale, and that of culturally taxonomic artefact classification [see e.g. @dunnell1971; @obrien2002; @reynolds2019; @riede2022]. @bjerck1987 states that typology obviously has its place as a culturally responsive framework for classifying artefact variation over time and space. Here I understand typology to be meant in a wide sense, pertaining both to the act and result of classifying artefacts, and its potential role as a dating method [see references above and e.g. @berg2021, 59--65; @graslund1987; @sørensen2015; for discussions concerning the term typology]. By ignoring this cultural dimension, chronozones, on the other hand, are supposed to facilitate comparisons across taxonomically inferred boundaries in space and time.

In her comment to Bjerck's paper, @skar1987[35] notes that geological chronozones couple pan-regional stratigraphic layers with the calendar scale, but that there are no equivalent pan-regional archaeological phenomena that equally consistently correspond to a section of the calendar scale. As @bjerck1987[40] further underscores in his response, archaeological chronozones are therefore not, unlike typological frameworks, meant to be culturally responsive, but are to represent a neutral temporal scale, typically instantiated as 500-year intervals. However, as @østmo1987 and @mikkelsen1987 note in their comments to Bjerck's original paper, this purpose is already fulfilled by the calendar. If the stratigraphic information related to a specific time-interval is removed from the geological chronozone, only \'chrono\' remains. Similarly, if the archaeological chronozone is not meant to hold any culturally responsive component, only the time-scale remains. 

As a culturally independent scale, the calendar scale will always be preferable to the that of chronozones. Not only because it is firmly established, but also because it already allows for more variation in the temporal resolution associated with different phenomena to be systematised, and allows for their duration and uncertainty of occurrence to span a wider range of aggregative time-units [cf. @reitan2022, 187]. The ability to shift and readjust the temporal resolution depending on the phenomena one is attempting to align and contrast is important as ‘different timescales bring into focus different sorts of processes, requiring different concepts and different sorts of explanatory variables’ [@bailey1987, 7; @bailey2007].

In replying to this critique, @bjerck1987[40] states that questioning the need of chronozones when we already have the calendar is like asking \'Do we need the term "month" when we have numbered days?\'. This would seem to imply that chronozones, like the month, is to be of a predefined duration, at least within any individual study, and that variable duration and temporal uncertainty of different phenomena to be analysed must be collapsed into these aggregative units. Another issue is also if the terminology used with chronozones is better than simply stating what time-intervals we are dealing with. For example, @bjerck2008 uses the term Middle Mesolithic (MM) to denote the three chronozones MM1, 8000--7500 BCE; MM2, 7500--7000 BCE; and MM3, 7000--6500 BCE. A reader coming across \'MM3\' instead of \'7000--6500 BCE\', or some other more neutral name, therefore has to keep in mind that this simply refers to this specific time-interval. The term Middle Mesolithic should be entirely disregarded, as it is in this use meant to be devoid of any cultural meaning. 

One could perhaps change terminology to something that doesn't have as many cultural and research historical connotations as the Middle Mesolithic, but it strikes me as altogether unnecessary to do this via the chronozone, as this is simply solved by establishing a reference frame only using the calendar scale in the first place. If one wants to use a time-scale of 500-year intervals it would in my mind be better to simply define this independently of the now inflated discussion of chronozones, not least because I believe the discussions of the concept demonstrates that its use can lead to unnecessary confusion -- if not for practitioners, then likely for readers.

In their comments to the original paper by @bjerck1986, @østmo1987 and @mikkelsen1987 deem chronozones an unnecessary and complicating concept. Commenting on these critiques, @nyland2016[53--56] states that both Østmo and Mikkelsen make their comments considering typological frameworks for Mesolithic south-eastern Norway, but that neither address the issue of the geographical coverage that these have. However, this is first and foremost an empirical issue rather than something to be solved by new terminology, and clearly not by the chronozone, which is a concept meant to be culturally unresponsive. 

Drawing on an example given by @nyland2016[55]; if the question is if central Norway falls within the same cultural sphere as south-eastern Norway, understood to be determined by comparable material culture, then this is dependent on two dimensions, assuming the problem of the initial delineation of these two regions has been resolved. The first is an evaluation of the degree to which characteristics of archaeological material in the two regions is considered to be similar, according some criteria. The second pertains to the timing of the occurrence of this material. To establish this necessarily demands temporal data that is independent of the typological framework itself, or possibly by reference to some principle of seriation with the uncertainty that this entails [e.g. @dunnell1970]. If a set of artefact types occurs in both central Norway and south-eastern Norway, this could lead one to suggest that a similar kind of cultural expression is common to the two regions. If independent temporal data associated with this material, such as radiocarbon dates, additionally indicates that there is a temporal synchroneity between their occurrence, then this would lead one to conclude that this cultural expression appears to occur simultaneously -- within some level of temporal certainty. Depending on the magnitude of artefactual and temporal evidence for this coincidence, this could then lead one to apply this typological framework as a dating method in the case that one excavates a site in either region and discovers material of the type in question. A continuous adjustment and evaluation of the reliability of the identified cultural affinity and the derived typological dating frame will of course be necessary, but it will have to be founded on material culture and the position of their occurrence on the calendar scale. This also pertains to the co-occurrence of various archaeological evidence and their wider cultural implications, for example whether or not some artefact type tends to be associated with agricultural activity. If either region lack artefactual or temporal data, then either the nature or the timing of cultural affinity cannot be resolved. The concept of chronozones cannot overcome these issues, and, I think, is more likely to confuse them. 

I therefore agree with @østmo1987 and @mikkelsen1987 in that the concept of chronozones represents an unnecessary complication. Although some of these complications follow from misunderstandings of the original proposition [as pointed out by @bjerck1987, 40; @nyland2016, 55], this only underscores that the concept sometimes leads to the muddling of several spatial, temporal and culturally taxonomic issues. These are therefore arguably best handled by reference to already well-established terminology, and by the use of modern methods that allows for the formal definition and handling of fuzzy and uncertain categorisation in the aggregation of data, both on the scale of material culture, time and space [e.g. @bayliss2007; @crema2012; @fusco2020; @bevan2021; @shennan2015; @leplongeon2020; @matzig2021; @riede2019].

The misunderstandings and the amount of ink now spent discussing chronozones also means that invoking archaeological chronozones carries with it the necessity to clarify how one intends to use it, which can be circumvented by avoiding the term altogether. Furthermore, as a term suggested for use in Pan-Scandinavian Mesolithic research, I believe this idiosyncratic terminology will also unnecessarily divorce the field from discussions of the same issues within archaeology more widely, while also making the field less accessible to outsiders, more difficult to couple with adjacent disciplines, and possibly lead to confusion with the geological chronozone. It is therefore unclear what the concept now provides beyond what well-established archaeological and colloquial terminology already covers, perhaps apart from making us aware of these universal archaeological issues.  

### Radiometric and archaeological dating methods

Rather than being based on predefined discrete time-intervals beyond the calendar scale, the analyses undertaken in the papers for this thesis largely rely on absolute dates from radiocarbon- and shoreline dating. These two methods can be denoted radiometric and archaeological dating methods, where the first category is based on a process of radioactive decay and the second is based on some regularity in human behaviour leading to predictable variation over time. In the case of shoreline dating, this follows from the proclivity of people to have continuously settled close to the shoreline throughout the Norwegian Mesolithic, where the coupling of this with the calendar scale follows from the timing of shifts in the relative sea-level. However, a note should also be made on the fact that radiometric dating is never purely based on a steady process of radioactive decay. Apart from interpretations to do with the calibration, reliability and sampling context of a radiometric date, this also has to be seen in light of other chronological information and the wider archaeological context [@wylie2017]. As with the process of shoreline displacement, the cessation of radiocarbon uptake in an organism also requires an interpretative step to be meaningfully associated with a cultural event of archaeological interest. 

It is important to underscore that given the scarcity of radiocarbon dates, and the relative low resolution of shoreline dates, typological frameworks responsive to temporal variation in material culture can most decidedly offer valuable chronological insights, even though this is not directly integrated in the studies undertaken for this thesis. Furthermore, while the analyses are done here using dating methods that largely operate irrespective of archaeological periodisation, the results are frequently narratively and informally associated with general cultural developments believed to characterise the Mesolithic of south-eastern Norway, as roughly outlined in Chapter \@ref(chapter2). This is predominately done in an approximate manner with reference to what are best viewed as temporally and spatially fuzzy frameworks and is based on the underlying logic that frequent co-occurrence of a range of material expressions in time and space, as suggested by others, reflects some level of meaningful cultural cohesion. This also means that the term culture is used in a loose archaeological sense and is not presumed to equate to a people or a unified unit in terms of language, genetics, or social structures [see e.g. @roberts2011 for thorough discussions of the culture term as used in archaeology; and e.g. @riede2019 for perspectives that can be taken to challenge the rather naive view taken here]. While it appears reasonable to assume that such cohesion has largely resulted from the same cultural factors within the geographically limited area of south-eastern Norway through the Mesolithic, it is also worth noting that empirical correspondence can be driven by other factors. This includes cases where people have arrived at the same technology fulfilling the same purpose in disjoint regions of time and space, known as cultural convergence [e.g @mesoudi2011, 36--37], as well as cases where the same material expression has occurred across a range of different cultural and environmental settings to fulfil different purposes [as has been argued to be the case with slotted bone tool technology in Northern Europe, @manninen2021] -- effectively an example of equifinality.

Finally, it is worth commenting on the concept of non-linear time and temporality as it has been approached within archaeology and the humanities more widely. In an influential paper, @ingold1993 makes the distinction between chronology, history and temporality. Chronology is here defined as a sequence of regular time intervals in which events have occurred. History is defined as a series of events that can be aligned relative to each other by their occurrence within chronological intervals. These are thus sterile and homogeneous sequences, largely detached from a social reality. Temporality, on the other hand, pertains to how people perceive the flow of time and their own position within it, relative to both past and future. However, as @bayliss2007 point out, it is hard to see how the nature of temporality and the subjective and societal experience of time can be investigated without first establishing the sequence and duration of events on the calendar scale. To repeat @vankilde2007[22] as quoted in the introductory chapter: \'Chronology is the backbone of social interpretation.\' [see also e.g. @holdaway2008]. Focus is in this thesis therefore directed towards chronology and history (in Ingold's understanding) rather than temporality, as there are fundamental questions pertaining to the chronology of the Norwegian Mesolithic that remain unanswered. Improving our tools for establishing the chronology of events and its associated uncertainty can lay a critical foundation for future investigations of Mesolithic temporality and other non-linear conceptions of time [see e.g. @lucas2021; @nielsen2021c].

## Hunter-gatherers

The concept of hunter-gatherers here functions as a foundational heuristic model from which to derive empirical avenues to be explored, and to propose possible causal drivers behind any observed patterns [cf. @warren2022, 29]. Hunter-gatherers or foragers are useful but fuzzy and not unproblematic synonyms that are typically, but not exclusively, used to denote societies that have a diet based on non-agricultural produce [@kelly2013]. In the introduction to the seminal book *The Lifeways of Hunter-Gatherers: The Foraging Spectrum*, @kelly2013[4] states that he aims at providing his readers with \'some knowledge of the variation that exist among foragers and some idea of what accounts for it\'. Thus, while comprehensive in scope, @kelly2013 is also very explicit in the limitations of his review and states that while the hunter-gatherer term can be a useful heuristic and analytical unit for human societies, it carries no explanatory weight by itself [@kelly2013, 22]. The societal variation among more recent hunter-gatherer societies is immense, and as foraging has constituted the predominant life-way for humanity for 99% of its existence, the variation that can be expected among past hunter-gatherer societies is comparatively vast [e.g. @cummings2013, 33; @singh2022]. 

With the *Man the Hunter* conference in 1966, the so-called nomadic or generalised forager model was established, in which hunter-gatherer societies was seen as small and nomadic, characterised by being egalitarian, non-territorial, non-storing and low-violence [@lee1968]. As a response to the oversimplifying generalised foraging model, several authors pointed to examples of hunter-gatherers that deviated significantly from this model. As a consequence, several interrelated concepts were introduced as means with which to understand these deviations [e.g. @testart1982; @woodburn1982; see @grier2006; @kelly2013, 241--268; @lane2014], of which forager complexity has been especially influential to archaeology [@price1985]. In this understanding, societal complexity among foragers can include reduced residential mobility, increased population size and density, economic intensification, specialisation, and storage of resources, technological ratcheting involving increased number of artefact components and production steps, control of resources and territories, increased inter-group trade and conflict, elaboration of ceremonies and ritual behaviour, and increased social inequality with hierarchical differentiation in decision-making power [e.g. @arnold1996; @cummings2013, 55--74; @jeffery2020; @zvelebil1998; @price1985; @kelly2013, 241--242]. 

It is, however, important to note that complexity and simplicity are not value judgements concerning what constitutes a \'better\' or \'worse\' kind of societal organisation, nor does it entail that simple (sometimes termed generalised) foraging societies are easier to understand than those viewed as more complex. Furthermore, the distinction between simple and complex foragers should not be understood as a discrete dichotomy. The different components of what is often associated with degree of complexity is best conceived of not as a check-list, but rather as a complex web of interrelated societal variables that are merely collapsed under the complexity term. Different components of this concept will be variably relevant in any given context [e.g. @cummings2013] and these components can be variably related to societal complexity as conditions, consequences and causes for its emergence, permanence or lack thereof [@price1985a; @arnold1996]. Following from issues such as those listed above, some authors have deemed the complexity term inappropriate [e.g. @kelly2013; @warren2005]. However, I believe it can still inform some, but certainly not all features of hunter-gatherer societies that are of interest to elucidate, as long as care is taken to avoid a search for complexity in itself -- which can lead one to force the empirical record to accord with some idealised expectation of what characterises complex hunter-gatherers. Rather than searching for complexity, a better goal is to identify how and in what ways a society is more or less characterised by explicit dimensions of forager complexity [see @warren2005, 75], and realise that employing this heuristic model reduces the variation we can hope to discern to the idealising confines of the model [@cummings2013, 74].

With increased concern for the diversities that exist among hunter-gatherers, researchers have, at least from the 1980s, increasingly focused on the immense variation that has been demonstrated and can be expected among both extant and past hunter-gatherers [e.g. @arnold1996; @arnold2016; @price1985a; @lewin1988; @kelly2013; @singh2022]. As a consequence, this thesis attempts to balance some insights from hunter-gatherer studies more widely, with an open and exploratory perspective. While preconceptions of hunter-gatherer societies necessarily dictates some of the analytical avenues taken and influence the type of questions that are asked, the aim is to map variation in the dimensions of interest and have idiosyncrasies of the archaeological record from coastal south-eastern Norway dictate the conclusions that are reached. 

A further underlying issue with employing the hunter-gatherer society as a heuristic category with which to approach the material, are ways in which the history of research into such societies might inadvertently dictate how the data is treated. For example, a unilineal socio-evolutionary perspective was a fundamental influence at the inception of the research into hunter-gatherers [e.g. @kelly2013, 4--7]. While such views are deemed a grossly inappropriate reference frame today, it can be difficult to fully grasp and account for ways in which this influences the fundamental categories we operate with, however divorced they may now appear. Related concerns have also been voiced in Norwegian Mesolithic research, where for example @åstveit2014 is vary that a view of EM societies as highly mobile and LM societies as more sedentary might, at least in part, follow from an implicit view of prehistory as characterised by a continuous trajectory towards increased societal complexity. This implicit view might have forced us to cast the material traces available to us to meet these expectations.

Calls for more directed attempts at unveiling how such research-historical conditions might influence how we conduct Mesolithic research have recently been voiced [@elliott2022; @elliott2023]. While it is beyond the scope of this thesis to contribute much in the way of bringing these influences and their consequences to light, the next chapter will outline a framework that is employed in an attempt to clarify the evidential logic that underlies the undertaken studies. Hopefully, this can contribute to making evident where such biases might have influenced any analytical choices and the conclusions that are reached. 

### Hunter-fisher-gatherers

One implication of the defining economic characteristic of hunter-gatherers appears to be a case where environmental variation represents a considerable factor in structuring cultural variation. Environmental variability has been frequently shown to impact central aspects of forager societies, such as economy, population dynamics and mobility patterns, which in turn can be interrelated with virtually all dimensions of these societies [e.g. @binford1990; @bird2008; @kelly2013; @jorgensen2020a; @morgan2009; @hoebe2023; @ordonez2022].

However, while it appears to be the case that variables such as temperature and precipitation dictate general variability among prehistoric and historic hunter-gatherers, this has to be qualified. First of all, while this appears to be the case *in general*, it can hardly be assumed to apply uniformly to any individual case [see references above and e.g. @arponen2019; @johnson2014]. Understanding precisely what consequences variation in any single environmental variable has in any given case, if any, will be complicated by both the societal and environmental systemic wholes that respond to this variation, with some systems being more or less robust to such perturbations, depending also on the time-scale over which it operates and can be recognised archaeologically. While for example drought could intuitively be taken to represent a societal challenge, this certainly need not be the case. Drought might very well present more opportunities for resource exploitation than it eliminates [@arponen2019, 5--6 with further references], illustrating the point that any systemic variation, environmental or societal, can represent both threat and opportunity to systemic wholes, and simultaneously represent threat and opportunity to different parts of the systems. 

The further delineation of this thesis to focus on coastal areas has some further implications for what can be expected to be variables of concern for understanding the structure of the societies dealt with, indicated by the header of this section which includes the term \'fishers\'. Hunter-fisher-gatherers
is a term used by some scholars to underscore the economic significance of the utilisation of aquatic resources to some hunter-gatherer groups [@cummings2013, 22--24]. The term is generally meant to be used in an inclusive fashion, and can in addition to fishing thus also pertain to the exploitation of of marine mammals, shellfish and seabirds. Given the concentration of Mesolithic sites in the coastal areas of Norway, and the relative importance of marine resources that can be assumed from this, the term hunter-fisher-gatherer has been preferred by several scholars working with the material [e.g. @bergsvik2009b; @mansrud2018].

One reason that the coastal setting is of importance is that environments with a rich and stable access to resources has been argued by many authors to be more likely to support semi-sedentary, hierarchical foragers with higher population densities. This is found to commonly be associated with concentrated marine resources [e.g. @keeley1988; @smith2021; @singh2022], which are associated with a higher net productivity and ecological stability, with coastal areas representing ecotones that give rise to multiple niches conductive of species diversity [e.g. @yesner1980]. However, as with the role of other environmental conditions for impacting the social structure of hunter-gatherers, important variation exists within these general trends. As a consequence, @jeffery2020 have argued that there has been a tendency of oversimplifying and reducing the adaptational diversity among foragers utilising aquatic resources, reminiscent of the earlier oversimplifications of hunter-gatherers in general [see also @bailey2002; @erlandson2001]. As this study is limited to studying the developments within the coastal region of south-eastern Norway, it is not in a position to inform the question of how coastal adaptation might be conductive of other societal configurations than terrestrial adaptation. It can, however, potentially illuminate regionally internal variation in coastal adaptation over time.

A note should be made on the fact that in the literature the terms *coastal adaptation* and *coastal resource use* are sometimes taken to imply different and quite specific things [see e.g. @faulkner2021; @marean2014; @will2019]. Coastal resource use is in this understanding seen as something that is conducted sporadically or occasionally, and that has limited transformative feedback effects on the life-ways of the societies in question. Conversely, coastal adaptation involves a degree of coastal engagement and commitment that has an altering effect on these societies. I do not use the terms in this manner here. The conceptual distinction is certainly an important one, especially as marine exploitation is believed to potentially, but not necessarily [e.g. @erlandson2001], lead to technological ratcheting and increased societal complexity. However, these quite specific connotations of the terms stand in danger of leading to misunderstandings for readers that have another understanding of adaptation, which need not be defined by some threshold in the intensity of coastal engagement. One response to the specifics of a given coastal habitat might for example be movement and extended use of terrestrial resources, which would fall within a more inclusive definition of adaptation to a given coastal environment. While the above division might have merit in some analytical settings, the dependence on marine resources is arguably better understood along a continuum that I believe this distinction might unnecessarily dichotomise.

### Land-use and mobility patterns {#mobility}

As it is fundamental for subsistence search, mobility patterns is considered defining of hunter-gatherer societies [e.g. @kelly2013, 77--113; @singh2022]. Important characteristics related to land-use and mobility patterns is the range of movement, its frequency, the degree to which movement ranges are territorially defined, where in the landscape movement and occupation occurs, the degree to which this is related to different kinds of activities, and the degree to which these aspects varies annually, with the seasons or other temporal frequencies. Furthermore, as mobility operates at the level of individuals, the degree to which people have moved as individuals or in groups, and what kinds of people have moved is ultimately also collapsed within the mobility term [@kelly1992]. From an archaeological perspective, however, occupational duration is often considered the most important dimension of hunter-gatherer mobility [@grove2009]. This follows both from the structuring effect this has on the activities carried out by members of these societies, from its frequent correlation with a range of other indicators of societal complexity, and from the expectation that occupational duration should be reflected in characteristics of the available archaeological material. However, the role of occupational duration as either a potential pre-requisite, cause or mere covariate with other dimensions of societal complexity cannot be assumed for any given case, and is also likely to play into a complex web of interrelated societal feedback effects.

One of the most central models with which to approach past hunter-gatherer mobility follows from Binford's [-@binford1980] distinction between foragers and collectors. Foragers are generally characterised by higher residential mobility, involving the movement of all members between residential bases, while collectors are associated with a higher degree of logistic mobility, involving the temporary excursion of task-groups from more permanent residential bases to fulfil specific tasks. @binford1980 argued that foragers are more common in environmentally homogeneous regions, while collectors are more common in regions exhibiting temporal and spatial variation in available resources.

The mid-latitude coastal setting of this thesis could thus have some general implications for what might be expected in terms of mobility patterns. Based on historically known hunter-gatherers, @binford1990 has argued that a semi-nomadic mobility pattern dominate in higher latitude settings. This involves a reduction in residential mobility in the winter months, where settlements are established close to stable resource patches or stored foods, and foragers utilising aquatic resources will, in general, be characterised by highly logistical mobility patterns. Furthermore, @binford1990 also argued that in higher latitude settings there is generally a lower dependence on plant foods, and a tendency for this to be replaced by the exploitation of aquatic resources, rather than terrestrial hunting and trapping. The exploitation of aquatic resources such as fish and marine mammals can in turn have implication for technological complexity, where a dependency on elaborate boating and catching technologies can follow from the challenges posed by hunting aquatic resources [e.g. @arnold1995; @kelly2013, 127]. 

@lane2014 has argued that while there is a general consensus on the heuristic value of the forager/collector distinction, he also underscores that these are the extreme ends of a continuum, as @binford1980 also originally contended, and that most forager populations have mobility patterns that fall somewhere between these extremes. While it might very well be the case that that higher latitude hunter-fisher-gatherers are generally associated with a higher logistical as opposed to residential mobility patterns, the degree to which this has been the case and might have varied throughout the coastal Mesolithic of south-eastern Norway must still be considered undetermined. While classic treatments of hunter-gatherer mobility such as that of @binford1990 do touch on the issue of aquatic hunter-gatherers, it has been argued that they often underestimate the implications of aquatic adaptation, and crucially the implications this has for these models to meaningfully track mobility patterns that involve traversing intricate coastlines and voyages to off-shore islands using water-going vessels [see  @ames2002; @yesner1980; @rowley-conwy2017]. However, despite the important nuances that might be subsumed within the forager--collector continuum, especially when applied to hunter-fisher-gatherers, @ames2002 maintains its heuristic value. Consequently, the forager--collector continuum and occupational duration are aspects of mobility that are in focus for this thesis. This is the direct concern of Paper 3, which attempts to illuminate these dimensions by drawing on the composition of the lithic inventories associated with sites in the study area [@roalkvam2022]. However, as outlined above, there are still a host of dimensions to mobility that are not captured by this framework and which decidedly warrant future investigation. 

### Responses to sea-level change

In most areas of the world, post-glacial sea-level change has involved inundation of vast areas that were previously inhabited. For Europe alone, @bailey2020[2] give the estimate that around 2.5 million km^2^ have been submerged following the Last Glacial Maximum, which equates to c. 40% of the present landmass. This has undoubtedly led to the destruction of vast amounts of archaeological material, and offers a considerable challenge to the retrieval of what archaeological material remains, and for efforts to reconstruct the past landscape in the impacted areas. This has been argued to have led to a reluctance on the part of archaeologists to contend with this challenging material, and to have resulted in an underestimation of the role that marine adaptation has played throughout prehistory [@bailey2002]. 

As was presented in Chapter \@ref(chapter2), unlike most areas of the world the study area for this thesis has been subject to a continuous and at times dramatic post-glacial relative sea-level fall. While methodological developments, new material and willingness to confront the issues posed by post-glacial relative sea-level rise have improved greatly in recent decades [see e.g. @bailey2020], the potential insight that can be gleaned from areas such as south-eastern Norway is therefore immense. This follows from the fact that the material has not been subject to the destruction and erosion that can follow from marine transgressions, and the retrieval of the material is comparatively easy, given that it is today located on dry land and has not been buried in thick layers of marine sediments. Mesolithic sites in the region are generally located at elevations that have historically not been impacted by the expansion of infrastructure or agriculture, and the sites are typically detectable through test-pit surveys that commonly encounter the material from c. 10--30 cm below the surface. While this has come at the cost of preservation of organic material, which is typically poor in the acidic Norwegian soils, it does, at the same time, offer a virtually unprecedented potential for mapping the distribution of a large number of sites through the relatively easily recovered lithics. Furthermore, while the reconstruction of past sea-level change is hefted with some challenges, these areas have not been impacted by the deposition of marine sediments following their emergence from the sea, which means that the landscape inhabited by Mesolithic populations is also comparatively easy to reconstruct.

Depending on its magnitude, sea-level change can impact not only the habitational suitability of any individual location, but can have far-reaching effects that impact shoreline morphology, drainage systems and oceanic circulation, in turn having a wide range of potential effects on the prehistoric societies that inhabited these areas [e.g. @akerlund1996; @astrup2018; @gross2018; @vaneeckhout2012]. While the at times dramatic sea-level change would have required a response from human populations residing in the impacted areas, it is by no means given that these would have negative societal effects. In fact, areas impacted by sea-level change can become increasingly attractive for hunting, fishing and gathering precisely because of these factors. @conneller2016, for example, argue that the rapidly changing coastal landscape associated with the isolation of the Channel Islands from the mainland made these especially attractive for settlement by Mesolithic populations. As with any environmental change, how sea-level change impacts the population of any given area will thus depend on a wide range of factors pertaining to the amplitude of shoreline displacement, the topographic setting, and the nature of the environmental and societal systems that respond to these changes [see references above and @barnett2020].

Sea-level regression would have had the consequences that present-day fjords would have been wider in prehistory, and other fjords, straits and waterways that are closed off today would have been present. In south-eastern Norway, the sea-level regression has impacted the shoreline morphology in various ways and at various scales. At the larger scale, the Oslo fjord itself would have been a larger bay in the early Holocene, which would, for example, have had consequences for the first human migration extending along the Norwegian coast [@glorstad2016]. Comparatively, the closing of specific straits, the forming of peninsulas by islands being connected to the mainland, or the emergence of islands from the sea might have had important consequences at a more local scale [see e.g. @mjærum2022]. Furthermore, with the emergence of land from the sea, the transition from oceanic, to littoral to terrestrial environments means that the coastal areas would have been characterised by a process of ecological change that continued also well after an area emerged from the sea  [@akerlund1996, 79; @wren2020].

Beyond impacting the physical and environmental conditions of the areas that these societies inhabited, a central premise for Norwegian Stone Age archaeology has been that people have continuously settled on or close to the shoreline throughout the Mesolithic [e.g. @brogger1905]. This has typically been related to resource exploitation and travel and communication by boat. The degree to which this settlement pattern holds through the period has fundamental societal implications, given the commitment to coastal adaptation such a settlement pattern can be assumed to reflect. However, it also underlies a method known as shoreline dating. Given the premise that sites were in use when located close to shoreline, it follows that a reconstruction of the trajectory of relative sea-level change can be drawn on to assign approximate date to when the sites were in use, based on their altitude relative to the present sea-level. Shoreline dating provides a valuable dating tool that allows us to date sites where typological indicators or radiometric dates are not available, and is fundamental to the chronological framework that underlies our understanding of the Norwegian Mesolithic. The first paper of this thesis involves a more principled evaluation of the relationship between sites and sea compared to what has been done in the past [@roalkvam2023], and the results of this analysis were then used to develop a more formalised method for shoreline dating that is made available as an R package through the second paper of the thesis [@roalkvam2023b]. 

### Palaeodemography {#demography}

Palaeodemography or the study of temporal and spatial variation in the size and structure of past populations is a fundamental problem for archaeology [e.g. @drennan2015; @french2021; @shennan2000; @kintigh2014]. This follows from the fact that demography is a central factor in processes such as genetic diversification, social network structure and scaling, as well as technological innovation and accumulation -- human culture is in large part determined by human interaction, which is dependent on population density. 

For example, the Late Glacial and early Post Glacial colonisation attempts of southern Scandinavia is characterised by a repeated sequence of technological loss which @riede2009 has related to demographic dynamics, drawing on Henrich's [-@henrich2004] model for reduction in technological complexity with demographic collapse [see also @premo2010a]. However, when considering the potential role of population increase or decline for societal change, it is important to consider the wider context in which these developments operate. This can be illustrated by the distinction between population density and population pressure which @keeley1988 emphasises. Population pressure is the combined effect of population density and available critical resources. Unless there is a catastrophic demographic collapse, increased population pressure can bring about changes to socio-economic complexity as an adaptational response, for example by economic intensification or diversification, storage or exchange, or with an increase in mobility [@halstead1989] -- population decline is therefore not necessarily or uniformly associated with reduction or increase in societal complexity [@collard2013a; @riede2014]. Understanding the consequences of changes in population dynamics and population structure is thus also dependent on knowledge of the nature and scale of the demographic development, as well as factors such as economic organisation and corresponding environmental carrying capacity. As a result, the role and potential feedback effects between population dynamics and other societal dimensions is contested in the literature [see e.g. @collard2013b; @currie2022; @vaesen2023; @read2020], and @collard2016 have cautioned that population characteristics should be considered *potential* explanatory variables for observed cultural change. It cannot be assumed *a priori* that population structure determines observed cultural variation, or that it does so in a uniform way, and so it is important that such explanations are compared, contrasted and variably included in a range of potential explanatory frameworks.

A central question in the reconstruction of population dynamics among past hunter-gatherers is related to what is known as the forager population paradox. This follows from the difference between the population growth rates among recent hunter-gatherer populations, which have been found to have an annual growth rate of around 1--3 %, and those that must have characterised prehistoric hunter-gatherer populations. @gurven2019 give the example that with a growth rate near 1% per annum, a population of 100 would reach close to modern population numbers of 7.5 billion in just 2000 years. Some processes must therefore have led to the near stationary population numbers throughout evolutionary history, which @gurven2019 argue is likely the result of oscillating cycles of population booms and busts [see also @chamberlain2009]. By contrasting archaeological population proxies with ethnographic and historical estimates, @tallavaara2021 have demonstrated how the scale over which these oscillations operate likely imply that common archaeological population proxies only puts us in a position to track average population size over the relative long term. This in turn has implications for the kind of questions we can hope to answer concerning variable population growth rates and their consequences [e.g. @brown2017; @sibly2002], and has to be kept in mind if archaeologically recognisable population changes are to be contrasted with other forms of cultural or environmental variation over time [@tallavaara2021].

Inferences concerning demographic developments in Norwegian Stone Age archaeology have traditionally been done by drawing on possible archaeological correlates such as the number and density of artefacts and sites [@olsen1984; @østmo1988]. Following developments in prehistoric demographic modelling more widely [e.g. @crema2022; @shennan2013; @timpson2014; @crema2021], such efforts have in recent years been directed towards analysing the summed probability distributions (SPDs) of ^14^C-dates [e.g. @jorgensen2020; @solheim2018; @solheim2020; @nielsen2019; @nielsen2021]. Modelling population dynamics by use of SPDs is based on the underlying logic that more people will have resulted in deposition and later retrieval of more dateable material [also known as the dates-as-data approach, after @rick1987]. However, there are a series of methodological and conceptual issues with this procedure, some of which have been dealt with, and others which are integrated into the methodology and needs to be accounted for when interpreting any results [see recent review by @crema2022].

One fundamental methodological issue follows from procedure of summing probabilities. Several authors have pointed to the fact that this operation entails a collapse of both the frequency of events and their uncertainties, thus rendering the final SPD difficult to interpret and not suitable for direct analysis [@blackwell2003; @crema2022; @timpson2021; @carleton2018]. Another issue pertains to the underlying logic that there is a direct connection between the magnitude of material that ends up being dated and the number of people responsible for this, and the degree to which this relationship is stable over longer periods of time and across economic and cultural systems [e.g. @freeman2018; @surovell2009a]. 

While various solutions and ways to contend with these issues have been proposed [cf. @crema2022], their magnitude and relevance can be difficult to properly assess for any given context without also drawing on additional data that can inform the corresponding developments of other relevant factors. Consequently, what both critics and proponents of the approach appear to agree upon is the importance of contrasting a range of population proxies while also accounting for other variables that might impact these. The fourth and final paper for this thesis therefore compares the frequency distribution of shoreline and radiocarbon dates over time, both of which have previously been compared for the purposes of modelling past population dynamics [@solheim2018; @jorgensen2020; @tallavaara2020]. This was done both to devise a methodology for using the newly developed method of shoreline for this purpose, and with the substantive goal of starting to unpack and understand how these proxies relate and what underlying factors could be driving their relationship.   

## Chapter summary

The first part of this chapter has outlined how fundamental problems relating to the resolution of the archaeological record in the dimensions of time, space and material culture has been contended with in the literature and how these are approached in this thesis. The second part of the chapter outlined some of the factors that are typically viewed as central for understanding past hunter-gatherer societies, and that dimensions related to mobility patterns, responses to sea-level change and demographic developments are the ones primarily dealt with in this thesis.

Preconceived notions of what has characterised hunter-fisher-gatherer societies will at some level necessarily impact how the material under study is interrogated. This follows both from what research questions are deemed central, and because these notions will have impacted how the material has been retrieved and recorded. These notions are therefore to some degree inescapable influences on any research into the Norwegian Mesolithic. However, in the next chapter I will argue how this should not lead to epistemic despair.