# Concluding remarks

Any attempts at describing or explaining the past involves abstraction that will necessarily hide variation and idiosyncrasies that could prove to be both important and interesting. Quantification is one system of representation that allows stringent comparability and analytical feasibility for large amounts of data. Furthermore, the material that has been and continues to be generated by archaeology is getting increasingly large, and any attempts at basic description and overview, let alone inference from these amounts of data require frameworks designed to. Consequently, at the cost of reducing the archaeological record to the logic of numbers, quantification offers the potential to yield insights that are simply not achievable by other means. 

@shennan1988[1] quotes Renfrew has having stated that \'the days of the innumerate are numbered\'. However, in 2004 @kristiansen2004[80] stated that quantitative methods were \'disastrously out of fashion\' in archaeology. This picture has changed considerably since 2004 and enthusiasm for such approaches need to be continuously tempered by a concern for the answers they can hope to answer, the nuances that they might subsume, and the intricacies of fruitfully and critically employing the methods. However, the the potential of quantitative approaches is far from having being adequately utilised in Norwegian archaeology. 

This thesis has shown some of the advantages quantitative methods can have. Through the four papers of the thesis, focus has been directed towards first exploring and deriving methods that can be used to meaningfully handle this material. The first two papers concerned the assessment and derivement of a new method for shoreline dating. Exploratory multivariate statistics were then used to assess the composition of a large number of lithic inventories and explore this variation over time. Finally, the method for shoreline dating was used to date a large number of sites within the study region and compared the derived summed probability of these dates to that of the summed probability of radiocarbon dates from within the same region. 

From a substantive perspective, these approaches allowed for insights concerning settlement patterns, mobility patterns and demographic developments. However, it also clear that the thesis has open up new lines investigation and provided methods for deriving empirical patterns that . In all of the undertaken studies ways in which the findings could be further tested and nuanced are provided, causal models underlying the a have been presented in this synopsis.

The first two papers of the thesis were concerned with assessing, proposing and making available for use as an R package a new method for the shoreline dating of coastal Stone Age sites within the study area. Chronological information is fundamental to archaeology, and so any method that can be drawn on to improve our control of when past events occurred is invaluable to the discipline. Furthermore, shoreline dating is especially important for Norwegian Mesolithic research given the generally poor preservation of organic material suitable for radiocarbon dating, and the vast amount of surveyed sites where other forms of temporal data is altogether limited or unavailable. However, as was made clear in the papers and this synopsis, the proposed method would benefit from a comprehensive suite of further exploration and independent testing of its applicability. Independent testing will be important for assessing its reliability, and an extensions to different areas, inclusion of more data or other variables that might be relevant to the site-sea relationship could reveal nuances that has implications for the method could be adjusted for different contexts. 

Finally, as the code used for employing the method and that used for its original development is made freely available, the approach can readily be extended to any area where geological control of past shoreline displacement is available. This will most immediately be relevant for other areas of Fennoscandia where shoreline dating has previously been applied, including large swathes of the coast of Norway [e.g. @bjerck2008], Finland [e.g. @tallavaara2020] and Sweden [e.g.]. However, the general principle of dating sites based on their distance to shifting shorelines could prove applicable to many areas of the world, including other areas with a continuous shoreline regression such as [@wren2020]. However, the same principle also extends to areas subjected to sea-level rise, pro

The third paper of the thesis was concerned with exploring the composition of lithic assemblages using multivariate statistics to structure and help consistently scale an analysis of a larger number of lithic assemblages, each of which number from a few hundred to several thousand artefacts. Apart from demonstrating some of the potential of these kinds of approaches, which have seen limited application in Norwegian Mesolitich research, the analysis also identified some patterns that were given a sub