\pagestyle{plain}
\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
# Papers {-}
\restoregeometry

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Paper 1 {-}
\large Roalkvam, I. 2023. A simulation-based assessment of the relation between Stone Age sites and relative sea-level change along the Norwegian Skagerrak coast. \textit{Quaternary Science Reviews}, 266:107880. DOI: \url{https://doi.org/10.1016/j.quascirev.2022.107880}
\restoregeometry

\includepdf[pages={-}]{papers/paper1.pdf}
\includepdf[pages={-}]{papers/paper1_corrigendum.pdf}


\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Paper 2 {-}
\large Roalkvam, I. 2023. shoredate: An R package for shoreline dating coastal Stone Age sites. \textit{Journal of Open Source Software}, 8(85):5337. DOI: \url{https://doi.org/10.21105/joss.05337}
\restoregeometry

\includepdf[pages={-}]{papers/paper2.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Paper 3 {-}
\large Roalkvam, I. 2022. Exploring the composition of lithic assemblages in Mesolithic south-eastern Norway. \textit{Journal of Archaeological Science: Reports}, 42:103371. DOI: \url{https://doi.org/10.1016/j.jasrep.2022.103371}
\restoregeometry

\includepdf[pages={-}]{papers/paper3.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Paper 4 {-}
\large Roalkvam, I. and Solheim, S. 2023. Comparing summed probability distributions of shoreline and radiocarbon dates from the Mesolithic Skagerrak coast of Norway. \textit{SocArXiv} pre-print, version 2. DOI: \url{https://doi.org/10.31235/osf.io/2f8ph}
\restoregeometry

\includepdf[pages={-}]{papers/paper4.pdf}

\pagestyle{plain}
\newgeometry{top=0.32\paperheight}
\setlength{\parindent}{0cm}
# Appendix {-}
The following sections holds supplementary material published with the papers. Note that all data, code, text and figures underlying the papers, the introductory text and all supplementary material is available through the online repositories listed in Section \@ref(open).
\restoregeometry
\newpage

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Supplementary material, Paper 1 {-}
\restoregeometry

\includepdf[pages={-}]{appendix/supplementary_paper1.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Supplementary material, Paper 2 {-}
The supplementary material for Paper 2 is PDF versions of HTML documents providing documentation for the R package *shoredate*. These can be viewed in their original interactive form on either the GitHub page for the package at https://github.com/isakro/shoredate, on the website of the package at https://isakro.github.io/shoredate/ or through the landing page for the package on CRAN: https://cran.r-project.org/package=shoredate.
\restoregeometry
\newpage

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
### Introduction to shoredate (README.rmd) {-}
\restoregeometry
\includepdf[pages={-}]{appendix/supplementary_paper2_1.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
### Vignette 1: Guide to using shoredate (shoredate.rmd) {-}
\restoregeometry
\includepdf[pages={-}]{appendix/supplementary_paper2_2.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
### Vignette 2: Extending shoredate (extending-shoredate.rmd) {-}
\restoregeometry
\includepdf[pages={-}]{appendix/supplementary_paper2_3.pdf}


\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
### Reference manual for shoredate (shoredate.pdf) {-}
\restoregeometry
\includepdf[pages={-}]{appendix/supplementary_paper2_4.pdf}

\newgeometry{top=0.4\paperheight}
\setlength{\parindent}{0cm}
## Supplementary material, Paper 3 {-}
\restoregeometry
\includepdf[pages={-}]{appendix/supplementary_paper3.pdf}